Use the @TestContainer annotation for resource injection. Add a new R…
arquillian/arquillian-testcontainers pull request #20
Opened 2024-07-03 04:21 UTC by jamezp

…equireDocker annotation to fail early if no docker is found.

This would replace #19 depending on which option we choose to use `@TestContainer` on the instance variable to create the test container.

This also adds a `@RequiresDocker` annotation to more quickly fail if docker is not available.

2024-07-03 22:03 UTC, jasondlee requested changes
Overall, it looks pretty good, especially the javadoc that's there. Wouldn't mind seeing more at the class level (as noted in one comment). A few other notes of varying importance in the review. :)

2024-07-03 22:03 UTC, jasondlee commented on src/main/java/org/jboss/arquillian/testcontainers/TestcontainerDescription.java
> + * @author <a href="mailto:jperkins@redhat.com">James R. Perkins</a>
An explanation of this class' raison d'etre would be nice (other classes as well) . :)

2024-07-03 22:05 UTC, jamezp commented on src/main/java/org/jboss/arquillian/testcontainers/ContainerInjectionTestEnricher.java
> +            checkForDocker(isDockerAvailable);
The only reason I left it here was for cases when there are no fields marked with `@Testcontainer`, we don't really need to check.

2024-07-03 22:05 UTC, jamezp commented on src/main/java/org/jboss/arquillian/testcontainers/ContainerInjectionTestEnricher.java
> +            }
Yes, I'll fix this.

2024-07-03 22:30 UTC, jamezp commented on src/main/java/org/jboss/arquillian/testcontainers/ContainerInjectionTestEnricher.java
> +            checkForDocker(isDockerAvailable);
Actually, maybe we should just remove this because we know docker is already available.

2024-07-04 01:55 UTC, jasondlee approved these changes

2024-07-04 01:55 UTC, merged

2024-07-04 01:55 UTC, jasondlee commented
Looks great. Thanks, @jamezp!

2024-07-04 02:12 UTC, jamezp commented
> Overall, it looks pretty good, especially the javadoc that's there. Wouldn't mind seeing more at the class level (as noted in one comment). A few other notes of varying importance in the review. :)

Agreed. I want to update the README too. And think about some kind of document/examples.