Change annotation name
arquillian/arquillian-testcontainers pull request #43
Opened 2024-11-18 17:58 UTC by jasondlee

Rename DockerRequired to ContainerRequired
Clean up stray references to "docker"

Resolves #39.

2024-11-18 18:28 UTC, rhusar reviewed
I was hoping to some aggressive discussion/voting on that issue. I have to say my favorite is `@ContainerRuntimeRequired`.

2024-11-18 19:29 UTC, jasondlee commented
> I was hoping to some aggressive discussion/voting on that issue. I have to say my favorite is `@ContainerRuntimeRequired`.

And we can have that. :) I just pushed this so I didn't lose the changes I had locally.

2025-01-28 21:25 UTC, jamezp approved these changes

2025-01-28 21:39 UTC, rhusar requested changes
After more discussions with @jamezp I believe this should be actually called '@TestcontainersRequired'. What we need the annotation to specify, is that Testcontainers client works. This is to my knowledge currently the same as podman or docker required, but this may not always be the case. Also, that's what the implementation checks for.

2025-01-28 21:41 UTC, jamezp commented
> After more discussions with @jamezp I believe this should be actually called '@TestcontainersRequired'. What we need the annotation to specify, is that Testcontainers client works. This is to my knowledge currently the same as podman or docker required, but this may not always be the case. Also, that's what the implementation checks for.

This makes the most sense to me as well.

2025-01-28 21:51 UTC, jamezp commented on src/main/java/org/jboss/arquillian/testcontainers/api/Testcontainer.java
> + * // By throwing the TestAbortedException, the test will be skipped if a container engine is not available
This is a very minor comment. Should this "a Testcontainer engine"? I don't have a real strong opinion either way.

2025-01-28 21:53 UTC, rhusar commented on src/main/java/org/jboss/arquillian/testcontainers/api/Testcontainer.java
> + * // By throwing the TestAbortedException, the test will be skipped if a container engine is not available
I also think this needs a different wording, but I am not yet sure what's ideal wording is :)

2025-01-28 21:54 UTC, jasondlee commented on src/main/java/org/jboss/arquillian/testcontainers/api/Testcontainer.java
> + * // By throwing the TestAbortedException, the test will be skipped if a container engine is not available
I'm fine to leave it as is, but no strong opinion either. I think, though, that the "engine" is either Docker or Podman (at this point), whereas Testcontainers is the... orchestration tool that starts a "container" using whatever "engine" is available in the environment.

2025-01-28 21:55 UTC, jasondlee commented on src/main/java/org/jboss/arquillian/testcontainers/api/Testcontainer.java
> + * // By throwing the TestAbortedException, the test will be skipped if a container engine is not available
> I also think this needs a different wording, but I am not yet sure what's the ideal wording :)

Well, it seems that whole Javadoc is pretty outdated anyway. That sample code is pretty rough. Let me revisit that...

2025-01-28 21:56 UTC, rhusar commented on src/main/java/org/jboss/arquillian/testcontainers/api/Testcontainer.java
> + * // By throwing the TestAbortedException, the test will be skipped if a container engine is not available
Though "Testcontainer engine" is not a thing, how about going the descriptive way that "the test will be skipped if Testcontainers requirements are not available."

2025-01-28 22:06 UTC, jasondlee commented on src/main/java/org/jboss/arquillian/testcontainers/api/Testcontainer.java
> + * // By throwing the TestAbortedException, the test will be skipped if a container engine is not available
@rhusar  @jamezp, Updated the sample code and just removed the comment altogether.

2025-01-28 22:42 UTC, jamezp approved these changes
I'm good with whatever wording we choose. I like the annotation name so I'm approving :)

2025-01-29 14:23 UTC, jasondlee commented
I think we have a consensus, so I'm going to merge this. If you want any further changes, @rhusar, please follow up with an issue.

2025-01-29 14:23 UTC, merged

2025-01-29 14:24 UTC, rhusar commented
Agreed! Thanks.